#!/bin/bash
set -eux
set -o pipefail

# Install the selinux policy
[ -x /usr/sbin/semanage ] || exit 0

mkdir -p /opt/stack/selinux-policy

# Compile the selinux policy
checkmodule -M -m -o /tmp/ironic-ipxe.mod $(dirname $0)/../selinux/ironic-ipxe.te
sudo semodule_package -m /tmp/ironic-ipxe.mod -o /opt/stack/selinux-policy/ipxe.pp
