#!/bin/bash

set -eux

export DIB_REPOTYPE_nova=package
# export DIB_REPOTYPE_heat=package
# Still installing from git for heat for now, due to tripleo-heat-templates
# needing the OS::Heat::UpdateWaitConditionHandle functionality, which was not
# added until after the icehouse-2 tarball, and thus the rdo package.
export DIB_REPOREF_heat=5f0f9f213c6cf2ddc3ced5600efba72785a3e939

export DIB_REPOTYPE_keystone=package
export DIB_REPOTYPE_neutron=package
export DIB_REPOTYPE_glance=package
export DIB_REPOTYPE_swift=package
export DIB_REOTYPE_cinder=package

# Use packages for the clients
export DIB_REPOTYPE_python_cinderclient=package
export DIB_REPOTYPE_python_glanceclient=package
export DIB_REPOTYPE_python_heatclient=package
export DIB_REPOTYPE_python_keystoneclient=package
export DIB_REPOTYPE_python_neutronclient=package
export DIB_REPOTYPE_python_novaclient=package
export DIB_REPOTYPE_python_swiftclient=package
export DIB_REPOTYPE_python_ceilometerclient=package

export DIB_REPOTYPE_os_collect_config=tar
export DIB_REPOLOCATION_os_collect_config=http://tarballs.openstack.org/os-collect-config/os-collect-config-0.1.10.tar.gz
export DIB_REPOTYPE_os_refresh_config=tar
export DIB_REPOLOCATION_os_refresh_config=http://tarballs.openstack.org/os-refresh-config/os-refresh-config-0.0.7.tar.gz
export DIB_REPOTYPE_os_apply_config=tar
export DIB_REPOLOCATION_os_apply_config=http://tarballs.openstack.org/os-apply-config/os-apply-config-0.1.11.tar.gz
