#!/bin/bash

set -eux

export DIB_REPOTYPE_nova=tar
export DIB_REPOLOCATION_nova=http://tarballs.openstack.org/nova/nova-2014.1.b2.tar.gz

# The heat icehouse-2 tarball had a blocker bug
# export DIB_REPOTYPE_heat=tar
# export
# DIB_REPOLOCATION_heat=http://tarballs.openstack.org/heat/heat-2014.1.b2.tar.gz
export DIB_REPOREF_heat=5f0f9f213c6cf2ddc3ced5600efba72785a3e939

# Getting a 403 from:
# https://googledrive.com/host/0Bwh63zyus-UlZ1dxQ08zczVRbXc/ipaddr-2.1.11.tar.gz
# so, install keystone from package
export DIB_REPOTYPE_keystone=package
# export
# DIB_REPOLOCATION_keystone=http://tarballs.openstack.org/keystone/keystone-2014.1.b2.tar.gz

export DIB_REPOTYPE_neutron=tar
export DIB_REPOLOCATION_neutron=http://tarballs.openstack.org/neutron/neutron-2014.1.b2.tar.gz
export DIB_REPOTYPE_glance=tar
export DIB_REPOLOCATION_glance=http://tarballs.openstack.org/glance/glance-2014.1.b2.tar.gz
export DIB_REPOTYPE_swift=tar
export DIB_REPOLOCATION_swift=http://tarballs.openstack.org/swift/swift-1.11.0.tar.gz
export DIB_REOTYPE_cinder=tar
export DIB_REPOLOCATION_cinder=http://tarballs.openstack.org/cinder/cinder-2014.1.b2.tar.gz

# Use packages for the clients
export DIB_REPOTYPE_python_cinderclient=package
export DIB_REPOTYPE_python_glanceclient=package
export DIB_REPOTYPE_python_heatclient=package
export DIB_REPOTYPE_python_keystoneclient=package
export DIB_REPOTYPE_python_neutronclient=package
export DIB_REPOTYPE_python_novaclient=package
export DIB_REPOTYPE_python_swiftclient=package
export DIB_REPOTYPE_python_ceilometerclient=package

export DIB_REPOTYPE_os_collect_config=tar
export DIB_REPOLOCATION_os_collect_config=http://tarballs.openstack.org/os-collect-config/os-collect-config-0.1.10.tar.gz
export DIB_REPOTYPE_os_refresh_config=tar
export DIB_REPOLOCATION_os_refresh_config=http://tarballs.openstack.org/os-refresh-config/os-refresh-config-0.0.7.tar.gz
export DIB_REPOTYPE_os_apply_config=tar
export DIB_REPOLOCATION_os_apply_config=http://tarballs.openstack.org/os-apply-config/os-apply-config-0.1.11.tar.gz


