#!/bin/bash

set -eu
set -o pipefail

ANSWERSFILE=${ANSWERSFILE:-""}

if [ -z "$ANSWERSFILE" ]; then
    echo "\$ANSWERSFILE should be defined."
    exit 1
fi

file_list="$ANSWERSFILE
$TE_DATAFILE"

for f in $file_list; do
    cp "$f" "$TMP_HOOKS_PATH"
done
