#!/bin/bash

set -eu
set -o pipefail

ANSWERSFILE=${ANSWERSFILE:-""}

if [ -z "$ANSWERSFILE" ]; then
    echo "\$ANSWERSFILE should be defined."
    exit 1
fi

file_list="$HOME/.ssh/id_rsa_virt_power
$HOME/.ssh/id_rsa_virt_power.pub
/tmp/deploy-virt-overcloudrc
$ANSWERSFILE
$TE_DATAFILE
nodes.json"

for f in $file_list; do
    cp "$f" "$TMP_HOOKS_PATH"
done
