#!/bin/bash

export INSTACK_ROOT=${INSTACK_ROOT:-$(pwd)}
if [ "$INSTACK_ROOT" = "/usr/share" ]; then
    export INSTACK_TRIPLEO_SOURCE=${INSTACK_TRIPLEO_SOURCE:-"0"}
else
    export INSTACK_TRIPLEO_SOURCE=${INSTACK_TRIPLEO_SOURCE:-"1"}
fi
export TRIPLEO_ROOT=$INSTACK_ROOT

export PATH=$PATH:$INSTACK_ROOT/instack-undercloud:$INSTACK_ROOT/instack-undercloud/scripts:$INSTACK_ROOT/diskimage-builder/bin

export RUN_INSTACK=${RUN_INSTACK:-1}
export TRIPLEO_OS_DISTRO=fedora
export TRIPLEO_OS_FAMILY=redhat
export TE_DATAFILE=instack.json
export IMG_SOURCE_URL=http://file.rdu.redhat.com/~jslagle/tripleo-images-juno-source/

# Using delorean packages is no longer the default
export DELOREAN=${DELOREAN:-0}
export PACKAGES=${PACKAGES:-1}
# Using LKG is the default
export LKG=${LKG:-1}
# When using rdo-release, we default to rdo-juno
export RDO_RELEASE=${RDO_RELEASE:-"juno"}
export RDO_RELEASE_RPM=${RDO_RELEASE_RPM:-https://repos.fedorapeople.org/repos/openstack/openstack-juno/rdo-release-juno-1.noarch.rpm}

if [ "$PACKAGES" = "1" ]; then
    export JSONFILE=${JSONFILE:-$INSTACK_ROOT/instack-undercloud/json-files/fedora-20-undercloud-packages.json}
else
    export JSONFILE=${JSONFILE:-$INSTACK_ROOT/instack-undercloud/json-files/fedora-20-undercloud-source.json}
fi


export COMPLETION_MESSAGE="\
#############################################################################
install-undercloud complete.

The file containing this installation's passwords is at
/root/tripleo-undercloud-passwords.

There is also a stackrc file at /root/stackrc.

These files are needed to interact with the OpenStack services, and should be
secured. For convenience, they can be copied to the current directory:

sudo cp /root/tripleo-undercloud-passwords .
sudo cp /root/stackrc .

#############################################################################"

if [ "$LKG" = "1" ]; then
    export DELOREAN_REPO=http://209.132.178.33/repos/00/8f/008f5b67839ae03fa9a73ddc9a430c8312472e1a/delorean.repo
    export DELOREAN_REPO_ALT=http://209.132.178.33/repos/e3/af/e3af9b42b532363b6cdc8eb95207c7d5e0ea87fc/delorean.repo
else
    export DELOREAN_REPO=http://209.132.178.33/repos/current/delorean.repo
    export DELOREAN_REPO_ALT=http://209.132.178.33/repos/current/delorean.repo
fi

export PIP_DOWNLOAD_CACHE=~/.cache/pip

if [ "$LKG" = "1" ]; then
    # These are set manually, since they're not part of source-repositories
    export DIB_REPOREF_tripleo_image_elements=a64a3264de8136da4d30e2416f382b651754f035
    export DIB_REPOREF_diskimage_builder=97678dcda51cb70637daf8444206041f29e6a765
    export DIB_REPOREF_os_cloud_config=a2b5ec4d4d0f22dd58454023324d1245ecdeece7
    export DIB_REPOREF_tripleo_incubator=c3fb309727671130a32b4c19de48ec22c8530aa1

    # This is set manually since swift is not part of the undercloud
    export DIB_REPOREF_swift=4dc718e8c3bd2a8bbe1f2d7a98ad03421a70217f
    export DIB_REPOLOCATION_swift=https://git.openstack.org/openstack/swift.git

    # To generate these, run:
    # tripleo set-source-vars -m /etc/dib-manifests/dib-manifest-git-instack
    # after a successful installation.
    export DIB_REPOREF_ceilometer=85b859f42f10038edd22578cad266e5be58ceb01
    export DIB_REPOLOCATION_ceilometer=https://git.openstack.org/openstack/ceilometer
    export DIB_REPOREF_glance=b68c6471686163a9484058398fcb790ce578fb5e
    export DIB_REPOLOCATION_glance=https://git.openstack.org/openstack/glance.git
    export DIB_REPOREF_heat=1fdce41373bd8d160915b2e23dd4b176bd332d49
    export DIB_REPOLOCATION_heat=https://git.openstack.org/openstack/heat.git
    export DIB_REPOREF_horizon=ce839aa58d32a9bd475c099f371d0e820d51f1a3
    export DIB_REPOLOCATION_horizon=https://git.openstack.org/openstack/horizon
    export DIB_REPOREF_ironic=45b4ad3a303bc685b73d980a2abd8ae916c202ff
    export DIB_REPOLOCATION_ironic=https://git.openstack.org/openstack/ironic
    export DIB_REPOREF_keystone=a56d36311ca8a7e4ed6aa0f23685e9cb054dc27a
    export DIB_REPOLOCATION_keystone=https://git.openstack.org/openstack/keystone.git
    export DIB_REPOREF_neutron=48ec1fbfc3a96e1bac36d9089895966dee249538
    export DIB_REPOLOCATION_neutron=https://git.openstack.org/openstack/neutron.git
    export DIB_REPOREF_nova=3705f9ee565fa285c486652e35063636e34fa71e
    export DIB_REPOLOCATION_nova=https://git.openstack.org/openstack/nova.git
    export DIB_REPOREF_novnc=0ca7cf4867f1dae585d254f16ad62c552648265f
    export DIB_REPOLOCATION_novnc=https://github.com/kanaka/noVNC.git
    export DIB_REPOREF_python_ceilometerclient=ee32cf6fed677c4bf62e38b04167224f496eaebd
    export DIB_REPOLOCATION_python_ceilometerclient=https://git.openstack.org/openstack/python-ceilometerclient.git
    export DIB_REPOREF_python_cinderclient=4c8464114f5539706cffc6888ce007d0d3ceba16
    export DIB_REPOLOCATION_python_cinderclient=https://git.openstack.org/openstack/python-cinderclient.git
    export DIB_REPOREF_python_glanceclient=83808076a17970387aeabb8de75c5c9fa57634e5
    export DIB_REPOLOCATION_python_glanceclient=https://git.openstack.org/openstack/python-glanceclient.git
    export DIB_REPOREF_python_heatclient=c29f12a2a8f251573e537684c0b395d3039bbe9a
    export DIB_REPOLOCATION_python_heatclient=https://git.openstack.org/openstack/python-heatclient.git
    export DIB_REPOREF_python_ironicclient=b27fb0b31315a440d9e9103ab789652e912ddea8
    export DIB_REPOLOCATION_python_ironicclient=https://git.openstack.org/openstack/python-ironicclient.git
    export DIB_REPOREF_python_keystoneclient=4e4c757ccd6fddb05f0453e04bb444aa3a7da0c5
    export DIB_REPOLOCATION_python_keystoneclient=https://git.openstack.org/openstack/python-keystoneclient.git
    export DIB_REPOREF_python_neutronclient=ede859ebf6199e29d45978eb402c7c07f0170e75
    export DIB_REPOLOCATION_python_neutronclient=https://git.openstack.org/openstack/python-neutronclient.git
    export DIB_REPOREF_python_novaclient=3e5dae84a844f12cf27ea4800b96e18fb190148a
    export DIB_REPOLOCATION_python_novaclient=https://git.openstack.org/openstack/python-novaclient.git
    export DIB_REPOREF_python_swiftclient=45465c70e31764167b43fe342c38231a3e0b825c
    export DIB_REPOLOCATION_python_swiftclient=https://git.openstack.org/openstack/python-swiftclient.git
fi

export ELEMENTS_PATH=${ELEMENTS_PATH:-"\
$INSTACK_ROOT/instack-undercloud/elements:\
$INSTACK_ROOT/tripleo-image-elements/elements/:\
$INSTACK_ROOT/diskimage-builder/elements"}


