#!/bin/bash

export INSTACK_ROOT=${INSTACK_ROOT:-$(pwd)}
export TRIPLEO_ROOT=$INSTACK_ROOT

export PATH=$PATH:$INSTACK_ROOT/instack-undercloud:$INSTACK_ROOT/instack-undercloud/scripts:$INSTACK_ROOT/diskimage-builder/bin

export RUN_INSTACK=${RUN_INSTACK:-1}
export TRIPLEO_OS_DISTRO=fedora
export TRIPLEO_OS_FAMILY=redhat
export TE_DATAFILE=instack.json
export IMG_SOURCE_URL=http://file.rdu.redhat.com/~jslagle/tripleo-images-juno-source/

# Using delorean packages is the default
export DELOREAN=${DELOREAN:-1}
# Using LKG is the default
export LKG=${LKG:-1}

export COMPLETION_MESSAGE="\
#############################################################################
install-undercloud complete.

The file containing this installation's passwords is at
/root/tripleo-undercloud-passwords.

There is also a stackrc file at /root/stackrc.

These files are needed to interact with the OpenStack services, and should be
secured. For convenience, they can be copied to the current directory:

sudo cp /root/tripleo-undercloud-passwords .
sudo cp /root/stackrc .

#############################################################################"

if [ "$LKG" = "1" ]; then
    export DELOREAN_REPO=http://209.132.178.33/repos/0d/f4/0df4f416f9587881b8f7442b07506edf1155c3d3/delorean.repo
    export DELOREAN_REPO_ALT=http://209.132.178.33/repos/e3/af/e3af9b42b532363b6cdc8eb95207c7d5e0ea87fc/delorean.repo
else
    export DELOREAN_REPO=http://209.132.178.33/repos/current/delorean.repo
fi

export PIP_DOWNLOAD_CACHE=~/.cache/pip

if [ "$LKG" = "1" ]; then
    # These are set manually, since they're not part of source-repositories
    export DIB_REPOREF_tripleo_image_elements=5fea32ff79220fce2eb808d9b119832a98ace626
    export DIB_REPOREF_diskimage_builder=dbc60e8942ca700cd673a115a6d327af8ee41483
    export DIB_REPOREF_os_cloud_config=4a03e6b129c91a7269b6103a1f85fd011ec92c91
    export DIB_REPOREF_tripleo_incubator=c3fb309727671130a32b4c19de48ec22c8530aa1

    # This is set manually since swift is not part of the undercloud
    export DIB_REPOREF_swift=4dc718e8c3bd2a8bbe1f2d7a98ad03421a70217f
    export DIB_REPOLOCATION_swift=https://git.openstack.org/openstack/swift.git

    # To generate these, run:
    # tripleo set-source-vars -m /etc/dib-manifests/dib-manifest-git-instack
    # after a successful installation.
    export DIB_REPOREF_ceilometer=85b859f42f10038edd22578cad266e5be58ceb01
    export DIB_REPOLOCATION_ceilometer=https://git.openstack.org/openstack/ceilometer
    export DIB_REPOREF_glance=b68c6471686163a9484058398fcb790ce578fb5e
    export DIB_REPOLOCATION_glance=https://git.openstack.org/openstack/glance.git
    export DIB_REPOREF_heat=1fdce41373bd8d160915b2e23dd4b176bd332d49
    export DIB_REPOLOCATION_heat=https://git.openstack.org/openstack/heat.git
    export DIB_REPOREF_horizon=a56070d3587ee95667da0ceca84325934fac8ab3
    export DIB_REPOLOCATION_horizon=https://git.openstack.org/openstack/horizon
    export DIB_REPOREF_ironic=45b4ad3a303bc685b73d980a2abd8ae916c202ff
    export DIB_REPOLOCATION_ironic=https://git.openstack.org/openstack/ironic
    export DIB_REPOREF_keystone=a56d36311ca8a7e4ed6aa0f23685e9cb054dc27a
    export DIB_REPOLOCATION_keystone=https://git.openstack.org/openstack/keystone.git
    export DIB_REPOREF_neutron=48ec1fbfc3a96e1bac36d9089895966dee249538
    export DIB_REPOLOCATION_neutron=https://git.openstack.org/openstack/neutron.git
    export DIB_REPOREF_nova=3705f9ee565fa285c486652e35063636e34fa71e
    export DIB_REPOLOCATION_nova=https://git.openstack.org/openstack/nova.git
    export DIB_REPOREF_novnc=0ca7cf4867f1dae585d254f16ad62c552648265f
    export DIB_REPOLOCATION_novnc=https://github.com/kanaka/noVNC.git
    export DIB_REPOREF_python_ceilometerclient=ee32cf6fed677c4bf62e38b04167224f496eaebd
    export DIB_REPOLOCATION_python_ceilometerclient=https://git.openstack.org/openstack/python-ceilometerclient.git
    export DIB_REPOREF_python_cinderclient=4c8464114f5539706cffc6888ce007d0d3ceba16
    export DIB_REPOLOCATION_python_cinderclient=https://git.openstack.org/openstack/python-cinderclient.git
    export DIB_REPOREF_python_glanceclient=83808076a17970387aeabb8de75c5c9fa57634e5
    export DIB_REPOLOCATION_python_glanceclient=https://git.openstack.org/openstack/python-glanceclient.git
    export DIB_REPOREF_python_heatclient=c29f12a2a8f251573e537684c0b395d3039bbe9a
    export DIB_REPOLOCATION_python_heatclient=https://git.openstack.org/openstack/python-heatclient.git
    export DIB_REPOREF_python_ironicclient=b27fb0b31315a440d9e9103ab789652e912ddea8
    export DIB_REPOLOCATION_python_ironicclient=https://git.openstack.org/openstack/python-ironicclient.git
    export DIB_REPOREF_python_keystoneclient=4e4c757ccd6fddb05f0453e04bb444aa3a7da0c5
    export DIB_REPOLOCATION_python_keystoneclient=https://git.openstack.org/openstack/python-keystoneclient.git
    export DIB_REPOREF_python_neutronclient=ede859ebf6199e29d45978eb402c7c07f0170e75
    export DIB_REPOLOCATION_python_neutronclient=https://git.openstack.org/openstack/python-neutronclient.git
    export DIB_REPOREF_python_novaclient=3e5dae84a844f12cf27ea4800b96e18fb190148a
    export DIB_REPOLOCATION_python_novaclient=https://git.openstack.org/openstack/python-novaclient.git
    export DIB_REPOREF_python_swiftclient=45465c70e31764167b43fe342c38231a3e0b825c
    export DIB_REPOLOCATION_python_swiftclient=https://git.openstack.org/openstack/python-swiftclient.git
fi

export ELEMENTS_PATH="\
$INSTACK_ROOT/instack-undercloud/elements:\
$INSTACK_ROOT/tripleo-image-elements/elements/:\
$INSTACK_ROOT/diskimage-builder/elements/"

export DEPLOY_IMAGE_ELEMENT=deploy-ironic
export DEPLOY_NAME=deploy-ramdisk-ironic

export DEPLOY_DIB_EXTRA_ARGS=""
export DISCOVERY_DIB_EXTRA_ARGS=""

export DIB_COMMON_ELEMENTS=${DIB_COMMON_ELEMENTS:-""}
export DIB_COMMON_ELEMENTS="$DIB_COMMON_ELEMENTS element-manifest"

export OVERCLOUD_CONTROL_DIB_EXTRA_ARGS="\
baremetal \
base \
boot-stack \
ceilometer-agent-central \
ceilometer-agent-notification \
ceilometer-api \
ceilometer-collector \
cinder-api \
cinder-lio \
cinder-volume-nfs \
common-venv \
dhcp-all-interfaces \
haproxy \
horizon \
hosts \
keepalived \
mariadb-rpm \
neutron-network-node \
ntp \
os-collect-config \
pip-cache \
rabbitmq-server \
snmpd \
stable-interface-names \
stackuser \
swift-proxy \
swift-storage \
use-ephemeral \
selinux-policy-updates
"

export OVERCLOUD_COMPUTE_DIB_EXTRA_ARGS="\
baremetal \
base \
common-venv \
dhcp-all-interfaces \
hosts \
neutron-openvswitch-agent \
nova-compute \
nova-kvm \
nfs-client \
ntp \
os-collect-config \
pip-cache \
pypi-openstack \
snmpd \
stable-interface-names \
stackuser \
use-ephemeral
"

export OVERCLOUD_CINDER_DIB_EXTRA_ARGS="\
baremetal \
base \
cinder-lio \
cinder-volume-nfs \
common-venv \
dhcp-all-interfaces \
hosts \
ntp \
os-collect-config \
pip-cache \
pypi-openstack \
snmpd \
stable-interface-names \
stackuser \
use-ephemeral \
"

export OVERCLOUD_SWIFT_DIB_EXTRA_ARGS="\
baremetal \
base \
common-venv \
dhcp-all-interfaces \
hosts \
ntp \
os-collect-config \
pip-cache \
pypi-openstack \
snmpd \
stable-interface-names \
stackuser \
swift-storage \
use-ephemeral \
"

if [ "$DELOREAN" = "1" ]; then
    export DIB_COMMON_ELEMENTS="$DIB_COMMON_ELEMENTS delorean undercloud-package-install dib-run-parts-update"

    # Delorean is patched but there isn't a new build yet.
    export OVERCLOUD_CONTROL_DIB_EXTRA_ARGS="$OVERCLOUD_CONTROL_DIB_EXTRA_ARGS glance-wsme ceilometer-delorean dib-run-parts-update"
fi
