#!/bin/bash

set -eux
set -o pipefail

if rpm -q fedora-release; then
    if ! rpm -q openstack-ironic; then
        yum -y install openstack-ironic-common
    fi

    # https://bugzilla.redhat.com/show_bug.cgi?id=1154720
    chmod 0440 /etc/sudoers.d/ironic

    # Make sure python-netaddr is the latest version from RDO juno,
    # otherwise pip from ironic-discoverd will install a later version,
    # then the rpm update later will fail.
    yum -y update python-netaddr
fi
