#!/bin/bash

set -eux

TEMPLATE_PATH=$(os-apply-config --print-templates)

sed -i "s/\[baremetal\]/\[baremetal\]\nuse_file_injection=False/" $TEMPLATE_PATH/etc/nova/nova.conf
cat >> $TEMPLATE_PATH/etc/nova/nova.conf <<EOF
[libvirt]
inject_partition=-2
EOF
