#!/bin/bash

set -eux

sed -i "s/\[baremetal\]/\[baremetal\]\nuse_file_injection=False/" /opt/stack/os-config-applier/templates/etc/nova/nova.conf
cat >> /opt/stack/os-config-applier/templates/etc/nova/nova.conf <<EOF
[libvirt]
inject_partition=-2
EOF
