#!/bin/bash

set -eux

install-packages dnsmasq

pip install ironic-inspector
os-svc-daemon -n openstack-ironic-inspector -i /usr -u root -c ironic-inspector /etc/ironic-inspector/inspector.conf
install -d -m 0750 -o root -g root /etc/ironic-inspector

cat > /lib/systemd/system/openstack-ironic-inspector-dnsmasq.service << eof
[Unit]
Description=PXE boot dnsmasq service for ironic-inspector
After=openvswitch.service

[Service]
Type=forking
ExecStart=/sbin/dnsmasq --conf-file=/etc/ironic-inspector/dnsmasq.conf

[Install]
WantedBy=multi-user.target
Alias=openstack-ironic-inspector-dnsmasq.service
eof
