#!/bin/bash

set -eux
set -o pipefail

# Hack to work around the fact that newer versions of keystone in delorean
# require python-zope-interface, which isn't available on rhel7 right now.
if ! rpm -q python-zope-interface; then
    sudo yum install -y http://mirrors.kernel.org/fedora//releases/20/Everything/x86_64/os/Packages/p/python-zope-interface-4.0.5-2.fc20.x86_64.rpm
fi