#!/bin/bash

set -eux
set -o pipefail

# Jenkins seems to need starting..
systemctl start jenkins
systemctl status jenkins

# Wait Jenkins is up and running, it may take a long time.
if ! timeout 1000 sh -c "while ! curl -s http://localhost:8282 | grep 'No builds in the queue.' >/dev/null 2>&1; do sleep 10; done"; then
    echo "Jenkins is not up and running after long time."
    exit 1
fi

# Must remove the requires.txt for jenkins_job_builder as pip doesn't
# recongize that all the deps are already installed via distro packages, in
# particular, argparse is throwing it off
rm -f /usr/lib/python2.7/site-packages/jenkins_job_builder-1.1.0.post1-py2.7.egg-info/requires.txt

# Install the jenkins job builder jobs
cd /opt
git clone https://github.com/enovance/jjb-openstack.git jenkins_jobs
rm -fr /etc/jenkins_jobs
ln -s /opt/jenkins_jobs /etc/jenkins_jobs
/opt/jenkins-job-builder/jenkins_jobs/cmd.py update --delete-old /etc/jenkins_jobs/jobs

# Open iptables port for puppetmaster
add-rule INPUT -p tcp --dport 8140 -j ACCEPT
# Open iptables port for puppetdb
add-rule INPUT -p tcp --dport 8081 -j ACCEPT
# Open iptables port for jenkins
add-rule INPUT -p tcp --dport 8282 -j ACCEPT
# Allow traffic from instances to be forwarded via the install-server
add-rule FORWARD -s 192.0.2.0/24 -j ACCEPT

# Jenkins will need to ssh to each openstack-full instance, so give it stacks key
if [ ! -f /home/stack/.ssh/id_rsa ] ; then
    su stack -c 'ssh-keygen -N "" -f /home/stack/.ssh/id_rsa'
fi
mkdir -p ~jenkins/.ssh
cp ~stack/.ssh/id_rsa ~jenkins/.ssh/id_rsa
chmod 600 ~jenkins/.ssh/ ~jenkins/.ssh/id_rsa
chown -R jenkins ~jenkins/.ssh

# patch for hiera
curl https://raw.githubusercontent.com/enovance/edeploy-roles/master/files/backend.rb.patch | patch /usr/share/ruby/vendor_ruby/hiera/backend.rb -
