#!/bin/bash

set -eux
set -o pipefail

# Jenkins seems to need starting..
systemctl start jenkins
systemctl status jenkins

# Wait Jenkins is up and running, it may take a long time.
if ! timeout 1000 sh -c "while ! curl -s http://localhost:8282 | grep 'No builds in the queue.' >/dev/null 2>&1; do sleep 10; done"; then
    echo "Jenkins is not up and running after long time."
    exit 1
fi

# Must install python-ordereddict from epel, I don't know where else to get it
# for now.
yum install -y http://dl.fedoraproject.org/pub/epel/7/x86_64/p/python-ordereddict-1.1-6.el7.noarch.rpm
# Must also remove the requires.txt for jenkins_job_builder as pip doesn't
# recongize that all the deps are already installed via distro packages, in
# particular, argparse is throwing it off
rm -f /usr/lib/python2.7/site-packages/jenkins_job_builder-1.1.0.post1-py2.7.egg-info/requires.txt

# Install the jenkins job builder jobs
cd /opt
git clone https://github.com/hardys/jjb-openstack.git jenkins_jobs
rm -fr /etc/jenkins_jobs
ln -s /opt/jenkins_jobs /etc/jenkins_jobs
/opt/jenkins-job-builder/jenkins_jobs/cmd.py update --delete-old /etc/jenkins_jobs/jobs

# Open iptables port for puppetmaster
add-rule INPUT -p tcp --dport 8140 -j ACCEPT
# Open iptables port for puppetdb
add-rule INPUT -p tcp --dport 8081 -j ACCEPT
# Open iptables port for jenkins
add-rule INPUT -p tcp --dport 8282 -j ACCEPT
