#!/bin/bash

set -eux

install-packages dnsmasq

pip install ironic-discoverd
os-svc-daemon -n openstack-ironic-discoverd -i /usr -u root -c ironic-discoverd /etc/ironic-discoverd/discoverd.conf
install -d -m 0750 -o root -g root /etc/ironic-discoverd

cat > /lib/systemd/system/openstack-ironic-discoverd-dnsmasq.service << eof
[Unit]
Description=PXE boot dnsmasq service for ironic-discoverd
After=openvswitch.service

[Service]
Type=forking
ExecStart=/sbin/dnsmasq --conf-file=/etc/ironic-discoverd/dnsmasq.conf

[Install]
WantedBy=multi-user.target
Alias=openstack-ironic-discoverd-dnsmasq.service
eof
