#!/bin/bash

set -eux

mkdir -p /opt/stack/selinux-policy

# Adds policy that corrects the following AVC:
# type=AVC msg=audit(1405377840.548:23): avc:  denied  { name_connect } for pid=375 comm="haproxy" dest=5002 scontext=system_u:system_r:haproxy_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket
cp $(dirname $0)/../haproxy.pp /opt/stack/selinux-policy
cp $(dirname $0)/../haproxy.te /opt/stack/selinux-policy
