#!/bin/bash
# (re)starts the discovery dnsmasq process. This is just for
# plumbing... there is currently no configuration (eventually use
# os-apply-config to get a dnsmasq.conf)

set -eux

os-svc-enable -n openstack-ironic-inspector-dnsmasq
os-svc-enable -n openstack-ironic-inspector

os-svc-restart -n openstack-ironic-inspector-dnsmasq
os-svc-restart -n openstack-ironic-inspector
