#!/bin/bash

set -eux
set -o pipefail

DELOREAN_REPO=${DELOREAN_REPO:-""}

if [ -z "$DELOREAN_REPO" ]; then
    echo \$DELOREAN_REPO must be set
    exit 1
fi

sudo curl -o $TMP_MOUNT_PATH/etc/yum.repos.d/delorean.repo $DELOREAN_REPO
