#!/bin/bash

set -eux
set -o pipefail

DELOREAN_REPO=${DELOREAN_REPO:-""}

if [ -z "$DELOREAN_REPO" ]; then
    echo \$DELOREAN_REPO must be set
    exit 1
fi

sudo curl -o $TMP_MOUNT_PATH/etc/yum.repos.d/delorean.repo $DELOREAN_REPO
sudo curl -o $TMP_MOUNT_PATH/etc/yum.repos.d/delorean-alt.repo $DELOREAN_REPO_ALT
sudo sed -i "s/delorean/delorean-alt/g" $TMP_MOUNT_PATH/etc/yum.repos.d/delorean-alt.repo
