#!/bin/bash

set -eux

# newer openstack-keystone requires python-zope-interface, but that is not
# avaiable anywhere for EL7. So just install the Fedora package for now. We can
# add this dep to Delorean going forward.
if ! rpm -q python-zope-interface; then
    sudo yum install -y http://mirrors.kernel.org/fedora//releases/20/Everything/x86_64/os/Packages/p/python-zope-interface-4.0.5-2.fc20.x86_64.rpm
fi

# Services couldn't talk to mysql, disable selinux for now
sed -i -e 's/=enforcing/=permissive/g' /etc/selinux/config

yum install -y --nogpg puppet augeas rabbitmq-server openstack-keystone keepalived haproxy mariadb-galera-server ntp memcached mongodb-server xinetd mongodb grub2 bind-utils openstack-swift-account openstack-swift-container openstack-swift-object openstack-swift-proxy openstack-dashboard openstack-glance python-ceph os-net-config
