#!/bin/bash
set -ue

install -m 0755 -o root -g root $(dirname $0)/../../bin/discovery-mac-filter /usr/local/bin/discovery-mac-filter
cat > /etc/cron.d/discovery-mac-filter <<EOF

# Ensure we don't answer BOOTP for bare metal nodes that are already known and
# registered with Ironic (they are served by neutron-dhcp-agent).

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

* * * * * root discovery-mac-filter
EOF

