#!/bin/bash

set -eux

yum -y install \
    http://fedorapeople.org/~jomara/openstack-tuskar-0.2.2-2.fc20.noarch.rpm \
    http://fedorapeople.org/~jomara/openstack-tuskar-ui-0.1.0-2.fc20.noarch.rpm \
    http://fedorapeople.org/~jomara/python-tuskarclient-0.1.1-2.fc20.noarch.rpm

cp $(dirname $0)/../tuskar.conf /etc/tuskar/tuskar.conf
chown root:root /etc/tuskar/tuskar.conf
sed -i "s/%%ADMINPASSWORD%%/$UNDERCLOUD_ADMIN_PASSWORD/" /etc/tuskar/tuskar.conf
