#!/bin/bash

set -eux
set -o pipefail

#FIXME: this is a workaround for https://bugs.launchpad.net/oslo.config/+bug/1568820
yum install -y openstack-nova-common

# truncate nova.conf to avoid the duplicate sections that break puppet-nova's
# nova_config resource
cp /dev/null /etc/nova/nova.conf
