#!/bin/bash

set -eux
set -o pipefail

set +e
puppet apply --detailed-exitcodes /etc/puppet/manifests/puppet-stack-config.pp
rc=$?
set -e

echo "puppet apply exited with exit code $rc"

if [ $rc != 2 -a $rc != 0 ]; then
    exit $rc
fi
