#!/bin/bash

set -eux

if [ "$(grep "Fedora" /etc/redhat-release)" == "" ]; then
    REPO=epel-7/divius-ironic-discoverd-epel-7
else
    REPO=fedora-rawhide/divius-ironic-discoverd-fedora-rawhide
fi

curl -o /etc/yum.repos.d/divius-ironic-discoverd.repo https://copr.fedoraproject.org/coprs/divius/ironic-discoverd/repo/$REPO.repo
