#!/bin/bash

set -eux

yum -y install \
    http://kojipkgs.fedoraproject.org//packages/python-django-horizon/2014.1/0.9.b3.fc21/noarch/openstack-dashboard-2014.1-0.9.b3.fc21.noarch.rpm \
    http://kojipkgs.fedoraproject.org//packages/python-django-horizon/2014.1/0.9.b3.fc21/noarch/openstack-dashboard-theme-2014.1-0.9.b3.fc21.noarch.rpm \
    http://kojipkgs.fedoraproject.org//packages/python-django-horizon/2014.1/0.9.b3.fc21/noarch/python-django-horizon-2014.1-0.9.b3.fc21.noarch.rpm


pushd /usr/share/openstack-dashboard
python manage.py compress --force
popd


