#!/bin/bash

set -eux

# setup-baremetal requires this to be set
export TRIPLEO_ROOT=.
CPU=${CPU:-1}
MEM=${MEM:-2048}
DISK=${DISK:-30}
ARCH=${ARCH:-amd64}
MACS=${MACS:-"52:54:00:b5:bd:f0 52:54:00:f2:be:f0"}
PM_IPS=${PM_IPS:-}
PM_USERS=${PM_USERS:-}
PM_PASSWORDS=${PM_PASSWORDS:-}
setup-baremetal $CPU $MEM $DISK $ARCH "$MACS" undercloud "$PM_IPS" "$PM_USERS" "$PM_PASSWORDS"

# Must wait for baremetal nodes to register as nova hypervisors
sleep 60

setup-overcloud-passwords -o
source tripleo-overcloud-passwords

# Define the interface that will be bridged onto the Neutron defined
# network.
NeutronPublicInterface=${NeutronPublicInterface:-eth0}
# Define the overcloud libvirt type for virtualization. kvm for
# baremetal, qemu for an overcloud running in vm's.
OVERCLOUD_LIBVIRT_TYPE=${OVERCLOUD_LIBVIRT_TYPE:-qemu}

if [ -d /usr/share/tripleo-heat-templates ]; then
    tripleo-heat-merge \
        --included-template-dir /usr/share/tripleo-heat-templates \
        --scale NovaCompute=1 \
        /usr/share/tripleo-heat-templates/overcloud-source.yaml \
        /usr/share/tripleo-heat-templates/swift-source.yaml \
        /usr/share/tripleo-heat-templates/ssl-source.yaml \
        > overcloud.yaml
    OVERCLOUD_YAML_PATH=overcloud.yaml
else
    sudo make -C /opt/stack/tripleo-heat-templates overcloud.yaml COMPUTESCALE=1
    OVERCLOUD_YAML_PATH=/opt/stack/tripleo-heat-templates/overcloud.yaml
fi

heat stack-create -f $OVERCLOUD_YAML_PATH \
    -P AdminToken=${OVERCLOUD_ADMIN_TOKEN} \
    -P AdminPassword=${OVERCLOUD_ADMIN_PASSWORD} \
    -P CinderPassword=${OVERCLOUD_CINDER_PASSWORD} \
    -P GlancePassword=${OVERCLOUD_GLANCE_PASSWORD} \
    -P HeatPassword=${OVERCLOUD_HEAT_PASSWORD} \
    -P NeutronPassword=${OVERCLOUD_NEUTRON_PASSWORD} \
    -P NovaPassword=${OVERCLOUD_NOVA_PASSWORD} \
    -P NeutronPublicInterface=$NeutronPublicInterface \
    -P SwiftPassword=${OVERCLOUD_SWIFT_PASSWORD} \
    -P SwiftHashSuffix=${OVERCLOUD_SWIFT_HASH} \
    -P NovaComputeLibvirtType=$OVERCLOUD_LIBVIRT_TYPE \
    overcloud

wait_for 220 10 stack-ready overcloud

echo "Overcloud CREATE_COMPLETE"
