#!/bin/bash

set -eux

LOGFILE=~/.instack/install-undercloud.log

mkdir -p ~/.instack

exec > >(tee $LOGFILE)
exec 2>&1

# generate ssh authentication keys if they don't exist
if [ ! -f ~/.ssh/id_rsa ]; then
  ssh-keygen -t rsa -N ""  -f ~/.ssh/id_rsa
fi

# TODO: Workaround for:
# https://bugzilla.redhat.com/show_bug.cgi?id=1066983
sudo yum -y update vim-minimal

# TODO include tuskar-ui when available
sudo yum install -y openstack-tuskar
sudo yum install -y python-tuskarclient
# tuskar requires python-ipaddr, but it isn't a dep in the rpm
sudo yum install -y python-ipaddr

# TODO: move as a req in the rpm spec?
sudo yum -y install redhat-lsb-core

# TODO: should move as a req in rpm spec, installs semanage
sudo yum -y install policycoreutils-python

source ~/instack.answers

export LOCAL_IP
export DNSMASQ_START
export DNSMASQ_END
export LOCAL_INTERFACE
export MASQUERADE_NETWORK
export POWER_DRIVER
export VIRTUAL_POWER_USER
export VIRTUAL_POWER_HOST
export DHCP_START
export DHCP_END
export NETWORK_CIDR
export NETWORK_GATEWAY
export SSH_KEY

export UNDERCLOUD_DB_PASSWORD=${UNDERCLOUD_DB_PASSWORD:-$(tripleo os-make-password)}
export UNDERCLOUD_ADMIN_TOKEN=${UNDERCLOUD_ADMIN_TOKEN:-$(tripleo os-make-password)}
export UNDERCLOUD_ADMIN_PASSWORD=${UNDERCLOUD_ADMIN_PASSWORD:-$(tripleo os-make-password)}
export UNDERCLOUD_GLANCE_PASSWORD=${UNDERCLOUD_GLANCE_PASSWORD:-$(tripleo os-make-password)}
export UNDERCLOUD_HEAT_PASSWORD=${UNDERCLOUD_HEAT_PASSWORD:-$(tripleo os-make-password)}
export UNDERCLOUD_NEUTRON_PASSWORD=${UNDERCLOUD_NEUTRON_PASSWORD:-$(tripleo os-make-password)}
export UNDERCLOUD_NOVA_PASSWORD=${UNDERCLOUD_NOVA_PASSWORD:-$(tripleo os-make-password)}
export UNDERCLOUD_IRONIC_PASSWORD=${UNDERCLOUD_IRONIC_PASSWORD:-$(tripleo os-make-password)}

sudo -E instack \
  -p /usr/share/diskimage-builder/elements/ \
     /usr/share/tripleo-image-elements/ \
     /usr/share/instack-undercloud/ \
  -j /usr/share/instack-undercloud/json-files/fedora-20-undercloud-packages.json

sudo os-refresh-config

echo "install-undercloud Complete!"
