#!/bin/bash

set -eux

OS_AUTH_URL=${OS_AUTH_URL:-""}
if [ -z "$OS_AUTH_URL" ]; then
    echo "You must source a stackrc file for the Undercloud."
    exit 1
fi

# setup-baremetal requires this to be set
export TRIPLEO_ROOT=.
CPU=${CPU:-1}
MEM=${MEM:-2048}
DISK=${DISK:-30}
ARCH=${ARCH:-amd64}
MACS=${MACS:-"52:54:00:b5:bd:f0 52:54:00:f2:be:f0"}
PM_IPS=${PM_IPS:-}
PM_USERS=${PM_USERS:-}
PM_PASSWORDS=${PM_PASSWORDS:-}
tripleo setup-baremetal $CPU $MEM $DISK $ARCH "$MACS" undercloud "$PM_IPS" "$PM_USERS" "$PM_PASSWORDS"

# Must wait for baremetal nodes to register as nova hypervisors
sleep 60

tripleo setup-overcloud-passwords -o
source tripleo-overcloud-passwords

# Define the interface that will be bridged onto the Neutron defined
# network.
NeutronPublicInterface=${NeutronPublicInterface:-eth0}
# Define the overcloud libvirt type for virtualization. kvm for
# baremetal, qemu for an overcloud running in vm's.
OVERCLOUD_LIBVIRT_TYPE=${OVERCLOUD_LIBVIRT_TYPE:-qemu}

COMPUTESCALE=${COMPUTESCALE:-1}
BLOCKSTORAGESCALE=${BLOCKSTORAGESCALE:-1}
SWIFTSTORAGESCALE=${SWIFTSTORAGESCALE:-0}

if [ -d /usr/share/openstack-tripleo-heat-templates ]; then
    tripleo-heat-merge \
        --included-template-dir /usr/share/openstack-tripleo-heat-templates \
        --scale NovaCompute=$COMPUTESCALE \
        --scale BlockStorage=$BLOCKSTORAGESCALE \
        --scale SwiftStorage=$SWIFTSTORAGESCALE \
        /usr/share/openstack-tripleo-heat-templates/overcloud-source.yaml \
        /usr/share/openstack-tripleo-heat-templates/swift-source.yaml \
        /usr/share/openstack-tripleo-heat-templates/swift-storage-source.yaml \
        /usr/share/openstack-tripleo-heat-templates/ssl-source.yaml \
        /usr/share/openstack-tripleo-heat-templates/block-storage.yaml \
        > overcloud.yaml
    OVERCLOUD_YAML_PATH=overcloud.yaml
else
    sudo make -C /opt/stack/tripleo-heat-templates overcloud.yaml COMPUTESCALE=$COMPUTESCALE BLOCKSTORAGESCALE=$BLOCKSTORAGESCALE SWIFTSTORAGESCALE=$SWIFTSTORAGESCALE
    OVERCLOUD_YAML_PATH=/opt/stack/tripleo-heat-templates/overcloud.yaml
fi

heat stack-create -f $OVERCLOUD_YAML_PATH \
    -P AdminToken=${OVERCLOUD_ADMIN_TOKEN} \
    -P AdminPassword=${OVERCLOUD_ADMIN_PASSWORD} \
    -P CinderPassword=${OVERCLOUD_CINDER_PASSWORD} \
    -P GlancePassword=${OVERCLOUD_GLANCE_PASSWORD} \
    -P HeatPassword=${OVERCLOUD_HEAT_PASSWORD} \
    -P NeutronPassword=${OVERCLOUD_NEUTRON_PASSWORD} \
    -P NovaPassword=${OVERCLOUD_NOVA_PASSWORD} \
    -P NeutronPublicInterface=$NeutronPublicInterface \
    -P SwiftPassword=${OVERCLOUD_SWIFT_PASSWORD} \
    -P SwiftHashSuffix=${OVERCLOUD_SWIFT_HASH} \
    -P NovaComputeLibvirtType=$OVERCLOUD_LIBVIRT_TYPE \
    -P GlanceLogFile="''" \
    -P NeutronDnsmasqOptions="dhcp-option-force=26,1400" \
    overcloud

tripleo wait_for 220 10 stack-ready overcloud

echo "Overcloud CREATE_COMPLETE"

if [ -d /etc/tripleo ]; then
    TRIPLEO_ROOT=/etc/tripleo
else
    TRIPLEO_ROOT=/opt/stack/tripleo-incubator
fi

export OVERCLOUD_IP=$(nova list | grep notCompute0.*ctlplane | sed  -e "s/.*=\\([0-9.]*\\).*/\1/")

touch ~/.ssh/known_hosts
chmod 600 ~/.ssh/known_hosts
ssh-keygen -R $OVERCLOUD_IP

source $TRIPLEO_ROOT/overcloudrc

export no_proxy=${no_proxy:-""}
export no_proxy=$no_proxy,$OVERCLOUD_IP

tripleo init-keystone -p $OVERCLOUD_ADMIN_PASSWORD $OVERCLOUD_ADMIN_TOKEN \
    $OVERCLOUD_IP admin@example.com heat-admin@$OVERCLOUD_IP \
    ${SSLBASE:+--ssl $PUBLIC_API_URL}
tripleo setup-endpoints $OVERCLOUD_IP --cinder-password $OVERCLOUD_CINDER_PASSWORD \
    --glance-password $OVERCLOUD_GLANCE_PASSWORD \
    --heat-password $OVERCLOUD_HEAT_PASSWORD \
    --neutron-password $OVERCLOUD_NEUTRON_PASSWORD \
    --nova-password $OVERCLOUD_NOVA_PASSWORD \
    --swift-password $OVERCLOUD_SWIFT_PASSWORD \
    ${SSLBASE:+--ssl $PUBLIC_API_URL}
keystone role-create --name heat_stack_user
# setup-neutron "" "" 10.0.0.0/8 "" "" "" 192.0.2.45 192.0.2.64 192.0.2.0/24
NETWORK_CIDR=${NETWORK_CIDR:-"10.0.0.0/8"}
FLOATING_IP_START=${FLOATING_IP_START:-"172.17.0.45"}
FLOATING_IP_END=${FLOATING_IP_END:-"172.17.0.64"}
FLOATING_IP_CIDR=${FLOATING_IP_CIDR:-"172.17.0.0/16"}
tripleo setup-neutron "" "" $NETWORK_CIDR "" "" "" $FLOATING_IP_START $FLOATING_IP_END $FLOATING_IP_CIDR

nova flavor-delete m1.tiny
nova flavor-create m1.tiny 1 512 2 1

echo "Overcloud Deployed"
