#!/bin/bash

set -eux
set -o pipefail

sudo rpm -Uvh --force http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm
sudo rhos-release 6

# Enable the copr repo for our custom builds
sudo curl -o /etc/yum.repos.d/divius-instack-ironic-nova-epel-7.repo \
    https://copr.fedoraproject.org/coprs/divius/instack-ironic-nova/repo/epel-7/divius-instack-ironic-nova-epel-7.repo

sudo yum -y install instack-undercloud # need to get all the instack-undercloud deps
sudo rpm -evh instack-undercloud # the actual rpm is no longer needed

sudo yum -y install git

if [ ! -d "instack-undercloud" ]; then
    git clone http://github.com/agroup/instack-undercloud
else
    echo "WARNING##################################:"
    echo "instack-undercloud directory already exists, not recloning"
fi
