#!/bin/bash

set -eux

IMAGE_PATH=${IMAGE_PATH:-"."}

export DEPLOY_NAME=${DEPLOY_NAME:-deploy-ramdisk}

OS_AUTH_URL=${OS_AUTH_URL:-""}
if [ -z "$OS_AUTH_URL" ]; then
    echo "You must source a stackrc file for the Undercloud."
    exit 1
fi

# generate ssh authentication keys if they don't exist
if [ ! -f ~/.ssh/id_rsa ]; then
  ssh-keygen -t rsa -N ""  -f ~/.ssh/id_rsa
fi

if ! nova keypair-show default 2>&1 1>/dev/null; then
	tripleo user-config
fi

function check_image {
    local image_name=$IMAGE_PATH/$1

    if [ ! -f $image_name ]; then
        echo "$image_name does not exist."
        exit 1
    fi
}

function load_image {
    local image_name=$IMAGE_PATH/$1

    tripleo load-image -d $image_name
}

check_image $DEPLOY_NAME.initramfs
check_image $DEPLOY_NAME.kernel
check_image overcloud-control.qcow2
check_image overcloud-compute.qcow2
check_image overcloud-cinder-volume.qcow2
check_image overcloud-swift-storage.qcow2
check_image fedora-user.qcow2

load_image overcloud-control.qcow2
load_image overcloud-compute.qcow2
load_image overcloud-cinder-volume.qcow2
load_image overcloud-swift-storage.qcow2

glance image-delete bm-deploy-kernel 2>/dev/null || :
glance image-create --name bm-deploy-kernel --public \
    --disk-format aki < $IMAGE_PATH/$DEPLOY_NAME.kernel
glance image-delete bm-deploy-ramdisk 2>/dev/null || :
glance image-create --name bm-deploy-ramdisk --public \
    --disk-format ari < $IMAGE_PATH/$DEPLOY_NAME.initramfs

DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-"poc"}
if [ "$DEPLOYMENT_MODE" = "poc" ]; then
    if ! nova flavor-show baremetal 2>&1 1>/dev/null; then
        nova flavor-create baremetal auto 3072 30 1

        deploy_kernel_id=$(glance image-show bm-deploy-kernel | awk ' / id / {print $4}')
        deploy_ramdisk_id=$(glance image-show bm-deploy-ramdisk | awk ' / id / {print $4}')

        nova flavor-key baremetal set \
            "cpu_arch"="amd64" \
            "baremetal:deploy_kernel_id"="$deploy_kernel_id" \
            "baremetal:deploy_ramdisk_id"="$deploy_ramdisk_id"
    fi
fi
