#!/bin/bash

set -eu
set -o pipefail

SCRIPT_NAME=$(basename $0)

OS_AUTH_URL=${OS_AUTH_URL:-""}
if [ -z "$OS_AUTH_URL" ]; then
    echo "You must source a stackrc file for the Undercloud."
    exit 1
fi

function show_options () {
    echo "Usage: $SCRIPT_NAME [options]"
    echo
    echo "Deploys instances via Ironic in preparation for an Overcloud deployment."
    echo
    echo "Options:"
    echo "      --register-nodes    -- register nodes from a nodes json file"
    echo "      --nodes-json        -- nodes json file containing node data"
    echo "                             for registration."
    echo "                             Default: nodes.json in the current directory"
    echo "      --discover-nodes    -- Perform discovery of registered nodes."
    echo "                             Powers on registered nodes to complete"
    echo "                             the discovery process."
    echo "      --setup-flavors     -- Setup Nova flavors to match discovered"
    echo "                             profiles"
    echo "      --show-profile      -- Show matching profile of nodes"
    echo "      --deploy-nodes      -- Deploy nodes"
    echo "      --check-ssh         -- Check the root ssh connection to each"
    echo "                             deployed node."
    echo "      --delete-stack      -- Wait until the stack has deleted."
    echo "      --delete-nodes      -- Delete all nodes."
    echo "      --config-tools-provision"
    echo "                          -- Run provision.sh for config-tools"
    echo "      -x                  -- enable tracing"        
    echo "      --help, -h          -- Print this help message."
    echo
    exit $1
}

TEMP=$(getopt -o ,h -l,register-nodes,nodes-json:,discover-nodes,deploy-nodes,help,setup-flavors,show-profile,check-ssh,delete-stack,delete-nodes,config-tools-provision -o,x,h -n $SCRIPT_NAME -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

REGISTER_NODES=
NODES_JSON=
DISCOVER_NODES=
DEPLOY_NODES=
SETUP_FLAVORS=
SHOW_PROFILE=
CHECK_SSH=
DELETE_STACK=
DELETE_NODES=
CONFIG_TOOLS_PROVISION=
STDERR=/dev/null

DEPLOY_NAME=${DEPLOY_NAME:-"ironic-discover"}
IRONIC=$(keystone endpoint-get --service baremetal | grep publicURL | awk '{ print $4; }')
IRONIC=${IRONIC%/}

while true ; do
    case "$1" in
        --register-nodes) REGISTER_NODES="1"; shift 1;;
        --nodes-json) NODES_JSON="$2"; shift 2;;
        --discover-nodes) DISCOVER_NODES="1"; shift 1;;
        --show-profile) SHOW_PROFILE="1"; shift 1;;
        --deploy-nodes) DEPLOY_NODES="1"; shift 1;;
        --setup-flavors) SETUP_FLAVORS="1"; shift 1;;
        --check-ssh) CHECK_SSH="1"; shift 1;;
        --delete-stack) DELETE_STACK="1"; shift 1;;
        --delete-nodes) DELETE_NODES="1"; shift 1;;
        --config-tools-provision) CONFIG_TOOLS_PROVISION="1"; shift 1;;
        -x) set -x; STDERR=/dev/stderr; shift 1;;
        -h | --help) show_options 0;;
        --) shift ; break ;;
        *) echo "Error: unsupported option $1." ; exit 1 ;;
    esac
done

function register_nodes {
    NODES_JSON=${NODES_JSON:-"nodes.json"}
    NULL_STATS=${NULL_STATS:-0}
    tmp_json=$NODES_JSON
    if [ "$NULL_STATS" = "1" ]; then
        tmp_json=$(mktemp)
        jq '.nodes[].memory=null | .nodes[].disk=null | .nodes[].arch=null | .nodes[].cpu=null' $NODES_JSON > $tmp_json
    fi
    echo "  Registering nodes from $NODES_JSON"
    register-nodes --service-host undercloud --nodes <(jq '.nodes' $tmp_json) 1>/dev/null
    if [ "$NULL_STATS" = "1" ]; then
        rm -f $tmp_json
    fi
    echo "  Nodes registered."
    echo
    ironic node-list
    echo
}

function discover_nodes {

    # Reset edeploy state file to reset the role counts
    sudo cp /usr/libexec/os-apply-config/templates/etc/edeploy/state /etc/edeploy/state

    echo "  Discovering nodes."
    node_ids=$(ironic node-list | tail -n +4 | head -n -1 | awk -F "| " '{print $2}')
    token=$(keystone token-get | grep ' id ' | awk '{print $4}')
    for node_id in $node_ids; do
        echo -n "    Sending node ID $node_id to discoverd for discovery ... "
        # NOTE(dtantsur): this is not a stable CLI
        python -m ironic_discoverd.client introspect $node_id --auth-token $token
        # tftpd chokes when serving 4 or more clients. Seeing less than 3Mb/s
        # throughput. As a workaround, sleep for some time in between sending
        # each node to discovery to give each node enough time to download the
        # kernel/ramdisk before the next node is powered on.
        #
        # This seems to only affect certain environments, so don't use it for now.
        # sleep 10
        echo "DONE."
    done

    echo "   Polling discoverd for discovery results ... "
    for node_id in $node_ids; do
        echo -n "       Result for node $node_id is ... "
        while true; do
            res=$(python -m ironic_discoverd.client get_status $node_id --auth-token $token)
            if [[ "$(echo $res | jq '.finished')" != "false" ]]; then
                error=$(echo $res | jq '.error')
                if [ "$error" = "null" ]; then
                    echo "DISCOVERED."
                else
                    echo "ERROR: $error"
                fi
                break
            fi
            sleep 15
        done
    done

    # There is no way via Nova/Ironic to tell it which to port to use for
    # provisioning and thus create and associated Neutron port. When there is
    # more than 1 port, it will just pick the first one.  So, we need a hack to
    # delete discovered ports that are not on the provisioning network
    ports_to_delete=$(ironic port-list | grep 52:54 | awk '{print $2}')
    for p in $ports_to_delete; do
        tripleo wait_for 20 3 ironic port-delete $p
    done
}

function wait_for_ssh {
    echo "  Waiting for ssh as root to be enabled ... "
    echo
    ips=$(nova list | tail -n +4 | head -n -1 | awk '{print $12}' | cut -d= -f2)
    for ip in $ips; do
        echo -n "    checking $ip ... "
        tripleo wait_for 300 1 ssh -o "PasswordAuthentication=no" -o "StrictHostKeyChecking=no" root@$ip ls
        echo "DONE."
    done
    echo
}


function deploy_nodes {
    wait_for_hypervisor_stats
    DEPLOY_HEAT_TEMPLATE=${DEPLOY_HEAT_TEMPLATE:-"/usr/share/instack-undercloud/heat-templates/ironic-deployment.yaml"}
    CONTROL_COUNT=${CONTROL_COUNT:-"1"}
    COMPUTE_COUNT=${COMPUTE_COUNT:-"3"}
    echo "  Creating heat stack ... "
    heat stack-create $DEPLOY_NAME -f $DEPLOY_HEAT_TEMPLATE -P "control_count=$CONTROL_COUNT" -P "compute_count=$COMPUTE_COUNT"
    echo "  Created."
    echo
    echo -n "  Waiting for stack to finish ... "
    echo
    tripleo wait_for_stack_ready 60 10 $DEPLOY_NAME
    echo "DONE."
    heat stack-show $DEPLOY_NAME
    heat stack-list
    wait_for_ssh
    echo
}

function setup_flavors {
    if ! nova flavor-show baremetal_control 2>$STDERR 1>/dev/null; then
        echo "  Creating baremetal_control flavor ... "
        nova flavor-create baremetal_control auto 2048 40 1
    else
        echo "  baremetal_control flavor already exists."
    fi

    if ! nova flavor-show baremetal_compute 2>$STDERR 1>/dev/null; then
        echo "  Creating baremetal_compute flavor ... "
        nova flavor-create baremetal_compute auto 4096 40 1
    else
        echo "  baremetal_compute flavor already exists."
    fi

    deploy_kernel_id=$(glance image-show bm-deploy-kernel | awk ' / id / {print $4}')
    deploy_ramdisk_id=$(glance image-show bm-deploy-ramdisk | awk ' / id / {print $4}')

    echo
    nova flavor-list
    echo

    echo "  Setting baremetal_control flavor keys ... "
    nova flavor-key baremetal_control set \
        "cpu_arch"="x86_64" \
        "baremetal:deploy_kernel_id"="$deploy_kernel_id" \
        "baremetal:deploy_ramdisk_id"="$deploy_ramdisk_id" \
        "baremetal:localboot"="true" \
        "profile=control"
    nova flavor-show baremetal_control

    echo "  Setting baremetal_compute flavor keys ... "
    nova flavor-key baremetal_compute set \
        "cpu_arch"="x86_64" \
        "baremetal:deploy_kernel_id"="$deploy_kernel_id" \
        "baremetal:deploy_ramdisk_id"="$deploy_ramdisk_id" \
        "baremetal:localboot"="true" \
        "profile=compute"
    nova flavor-show baremetal_compute
}

function show_profile {
    node_ids=$(ironic node-list | tail -n +4 | head -n -1 | awk -F "| " '{print $2}')
    token=$(keystone token-get | grep ' id ' | awk '{print $4}')
    echo "  Querying assigned profiles ... "
    echo
    for node_id in $node_ids; do
        echo "    $node_id"
        echo -n "      "
        curl -s -H "x-auth-token: $token" $IRONIC/v1/nodes/$node_id | jq '.properties.capabilities'
        echo
    done
    echo
    echo "  DONE."
    echo
}

function wait_for_hypervisor_stats {
    node_ids=$(ironic node-list | tail -n +4 | head -n -1 | awk -F "| " '{print $2}')
    expected_nodes=$(echo $node_ids | wc -w)
    expected_memory=0
    expected_vcpus=0

    token=$(keystone token-get | grep ' id ' | awk '{print $4}')
    echo -n "  Wating for nova hypervisor stats ... "
    for node_id in $node_ids; do
        mem=$(curl -s -H "x-auth-token: $token" $IRONIC/v1/nodes/$node_id | jq '.properties.memory_mb | tonumber')
        vcpu=$(curl -s -H "x-auth-token: $token" $IRONIC/v1/nodes/$node_id | jq '.properties.cpus | tonumber')
        expected_memory=$(($expected_memory + $mem))
        expected_vcpus=$(($expected_vcpus + $vcpu))
    done

    tripleo wait_for 180 1 wait_for_hypervisor_stats $expected_nodes $expected_memory  $expected_vcpus

    echo "DONE."
    echo
}

function delete_stack {
    heat stack-delete $DEPLOY_NAME
    tripleo wait_for 90 2 ! heat stack-show $DEPLOY_NAME
}

function delete_nodes {
    for n in $(ironic node-list | tail -n +4 | head -n -1 | awk '{print $2}'); do
        ironic node-delete $n;
    done
}

function config_tools_provision {
    pushd /opt/stack/config-tools/
    sudo mkdir -p /var/www/install
    if [ -d /opt/stack/config-tools/env ] ; then
        pushd /opt/stack/config-tools/env
        sudo git reset --hard HEAD
        popd
    else
        sudo bash -x ./provision.sh master https://github.com/agroup/spinalstack-env.git/etest.yml version=master
    fi
    for x in 0 1 2; do
        sudo sed -i -e "s/SERVER$x/$(nova show openstack$x | grep ctlplane | grep -Eo "192[^ ]+")/g" env/etest.yml
        # Clean up certs from previous runs
        sudo puppet cert clean openstack$x.etest
    done
    sudo bash -x ./provision.sh -l master https://github.com/agroup/spinalstack-env.git/etest.yml version=master
    sudo rm -f /etc/config-tools/step
    popd
}

echo "Preparing for deployment..."

if [ "$REGISTER_NODES" = 1 ]; then
    register_nodes
fi

if [ "$DISCOVER_NODES" = 1 ]; then
    discover_nodes
fi

if [ "$SETUP_FLAVORS" = 1 ]; then
    setup_flavors
fi

if [ "$SHOW_PROFILE" = 1 ]; then
    show_profile
fi

if [ "$CHECK_SSH" = 1 ]; then
    wait_for_ssh
fi

if [ "$DELETE_STACK" = 1 ]; then
    delete_stack
fi

if [ "$DELETE_NODES" = 1 ]; then
    delete_nodes
fi

if [ "$CONFIG_TOOLS_PROVISION" = 1 ]; then
    config_tools_provision
fi

echo "Prepared."

if [ "$DEPLOY_NODES" = 1 ]; then
    echo "Deploying..."
    deploy_nodes
    echo "Deployed."
fi
