#!/bin/bash

set -eux
set -o pipefail

# Install repo file for Delorean master packages
# Pin to an older repo for now because newer openstack-keystone requires a
# newer and not yet avaialable python-pycadf.
export DELOREAN_REPO=${DELOREAN_REPO:-"http://trunk.rdoproject.org/centos70/2f/a5/2fa5839e2efc0f93c815aeff5ad0ddee1ba16830_d9a2ddd9/delorean.repo"}
sudo curl -o /etc/yum.repos.d/delorean.repo $DELOREAN_REPO
# We need to have the main delorean repo have a lower priority than ours to ensure our changes get installed
sudo sed -i 's/priority=1/priority=10/' /etc/yum.repos.d/delorean.repo

# Install repo file for Delorean el7 midstream packages built from
# rdo-management.
export DELOREAN_RHEL7_REPO=${DELOREAN_RHEL7_REPO:-"http://trunk-mgt.rdoproject.org/repos/current/delorean-rdo-management.repo"}
sudo curl -o /etc/yum.repos.d/delorean-rdo-management.repo $DELOREAN_RHEL7_REPO

# Delorean requires RDO
if ! rpm -q rdo-release; then
    sudo yum install -y https://rdo.fedorapeople.org/openstack-kilo/rdo-release-kilo-0.noarch.rpm
fi

if ! rpm -q epel-release; then
    sudo yum install -y http://mirrors.einstein.yu.edu/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
fi

if $(grep -Eqs 'Red Hat Enterprise Linux Server' /etc/redhat-release); then
    export RUN_RHOS_RELEASE=${RUN_RHOS_RELEASE:-"0"}
    # rhos-release is also required, otherwise we have no base RHEL repositories to
    # pull any dependencies from (without using subscription-manager anyway).
    if [ "$RUN_RHOS_RELEASE" = "1" ]; then
        if rpm -q rhos-release; then
            sudo yum remove -y rhos-release
        fi
        sudo yum install -y http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm
        sudo rhos-release 6
        # We need openwsman-python from the optional repo
        sudo yum install -y yum-utils
        sudo yum-config-manager --enable rhelosp-rhel-7-server-opt
    fi
fi

# Delorean uses repo priorities to ensure we get the right packages
sudo yum install -y yum-plugin-priorities
if [[ -f /etc/centos-release ]]; then
    # Use the Centos cloud repo to pull in its updated package lists
    cd /etc/yum.repos.d
    sudo curl -O http://buildlogs.centos.org/centos/7/cloud/openstack-rdo/centos-cloud-rdo.repo
fi
