#!/bin/bash

set -eu

export TUSKAR_URL=http://localhost:8585/

# delete the stack
OVERCLOUD_ID=$(tuskar overcloud-list | grep overcloud | awk '{print $2}')
tuskar overcloud-delete $OVERCLOUD_ID

SUCCESSFUL_MATCH_OUTPUT="Stack not found: overcloud" tripleo wait_for 12 10 heat stack-show overcloud

# cleanup the baremetal-nodes
node_ids=$(nova baremetal-node-list | grep undercloud | awk -F "| " '{ print $2; }')

for id in $node_ids; do
    nova baremetal-node-delete $id
done

glance image-delete bm-deploy-kernel || true
glance image-delete bm-deploy-ramdisk || true

nova flavor-delete baremetal || true
