#!/bin/bash

set -eux

LOGFILE=~/.instack/install-undercloud.log

mkdir -p ~/.instack

exec > >(tee $LOGFILE)
exec 2>&1

# generate ssh authentication keys if they don't exist
if [ ! -f ~/.ssh/id_rsa ]; then
  ssh-keygen -t rsa -N ""  -f ~/.ssh/id_rsa
fi

sudo yum -y install python-pip

# Workaround for:
# https://bugzilla.redhat.com/show_bug.cgi?id=1066983
sudo yum -y update vim-minimal

# Upstream dib is still needed due to environmentd patch
if [ ! -d diskimage-builder ]; then
  git clone https://git.openstack.org/openstack/diskimage-builder
  pushd diskimage-builder
  # Nothing special about this commit hash, just that it is latest known # working
  git reset --hard 39964b975e724cffaa0a94e80ed57ebff7221020
  sudo pip install -e .
  popd
fi

sudo yum install -y openstack-tripleo
sudo yum install -y openstack-tripleo-image-elements
sudo yum install -y openstack-tripleo-heat-templates

# Must delete packaged diskimage-builder for now b/c it is too old and messes
# up the install.
sudo rpm -e diskimage-builder --nodeps

# TODO include tuskar-ui when available
sudo yum install -y openstack-tuskar
sudo yum install -y python-tuskarclient

# Needed by source-repositories
sudo yum -y install tar

source ~/instack.answers

export LOCAL_IP
export DNSMASQ_START
export DNSMASQ_END
export LOCAL_INTERFACE
export MASQUERADE_NETWORK
export POWER_DRIVER
export VIRTUAL_POWER_USER
export VIRTUAL_POWER_HOST
export DHCP_START
export DHCP_END
export NETWORK_CIDR
export NETWORK_GATEWAY

sudo -E instack \
  -p diskimage-builder/elements/ \
     /usr/share/tripleo-image-elements/ \
     /usr/share/instack-undercloud/ \
  -j /usr/share/instack-undercloud/json-files/fedora-20-undercloud-packages.json

sudo os-refresh-config

echo "install-undercloud Complete!"
