#!/bin/bash

set -eux
set -o pipefail

export INSTACK_ROOT=${INSTACK_ROOT:-"/usr/share"}
source "$INSTACK_ROOT"/instack-undercloud/instack-sourcerc

sudo curl -o /etc/yum.repos.d/delorean.repo $DELOREAN_REPO
sudo curl -o /etc/yum.repos.d/delorean-alt.repo $DELOREAN_REPO_ALT
sudo sed -i "s/delorean/delorean-alt/g" /etc/yum.repos.d/delorean-alt.repo
sudo /bin/bash -c "echo >> /etc/yum.repos.d/delorean.repo"
sudo /bin/bash -c "echo 'exclude=openstack-tripleo openstack-tripleo-image-elements openstack-tripleo-heat-templates diskimage-builder dib-utils os-cloud-config openstack-ironic-api openstack-ironic-common openstack-ironic-conductor' >> /etc/yum.repos.d/delorean.repo"
sudo /bin/bash -c "echo >> /etc/yum.repos.d/delorean-alt.repo"
sudo /bin/bash -c "echo 'exclude=openstack-tripleo openstack-tripleo-image-elements openstack-tripleo-heat-templates diskimage-builder dib-utils os-cloud-config openstack-ironic-api openstack-ironic-common openstack-ironic-conductor' >> /etc/yum.repos.d/delorean-alt.repo"

