#!/bin/bash

set -eux

export INSTACK_ROOT=${INSTACK_ROOT:-$(pwd)}

export ELEMENTS_PATH="$INSTACK_ROOT/tripleo-image-elements/elements:$INSTACK_ROOT/diskimage-builder/elements:$INSTACK_ROOT/instack-undercloud/elements" 

export JSONFILE=$INSTACK_ROOT/instack-undercloud/json-files/fedora-20-undercloud-source.json

sudo yum -y install git python-pip

git config --global user.email "instack@example.com"
git config --global user.name "instack"

if [ ! -d $INSTACK_ROOT/tripleo-image-elements/elements ]; then
    git clone https://git.openstack.org/openstack/tripleo-image-elements
fi

if [ ! -d $INSTACK_ROOT/diskimage-builder/elements ]; then
    git clone https://git.openstack.org/openstack/diskimage-builder

    pushd diskimage-builder
    # https://review.openstack.org/#/c/105461/
    git fetch https://review.openstack.org/openstack/diskimage-builder refs/changes/00/105400/2 && git cherry-pick FETCH_HEAD
    # https://review.openstack.org/#/c/105543/
    git fetch https://review.openstack.org/openstack/diskimage-builder refs/changes/43/105543/1 && git cherry-pick FETCH_HEAD
    popd
fi


if [ ! -d $INSTACK_ROOT/instack-undercloud/elements ]; then
    git clone https://github.com/agroup/instack-undercloud
fi

if [ ! -d $INSTACK_ROOT/instack ]; then
    git clone https://github.com/agroup/instack
fi

pushd $INSTACK_ROOT/diskimage-builder
sudo pip install -e .
popd 

pushd $INSTACK_ROOT/instack
sudo pip install -e .
popd

$INSTACK_ROOT/instack-undercloud/scripts/instack-install-undercloud-packages
