#!/bin/bash

set -eux

LOGFILE=~/.instack/install-undercloud.log

mkdir -p ~/.instack

exec > >(tee $LOGFILE)
exec 2>&1

# generate ssh authentication keys if they don't exist
if [ ! -f ~/.ssh/id_rsa ]; then
  ssh-keygen -t rsa -N ""  -f ~/.ssh/id_rsa
fi

# Workaround for:
# https://bugzilla.redhat.com/show_bug.cgi?id=1066983
sudo yum -y update vim-minimal

# Need pip and git (due to pbr) to install instack since this is the source
# install.
sudo yum -y install python-pip git
pushd instack
  sudo pip install -e .
popd

# Must use updates-testing version of diskimage-builder (0.1.9) until it gets
# pushed to stable.
sudo yum -y --enablerepo=updates-testing update diskimage-builder

sudo yum install -y openstack-tripleo
sudo yum install -y openstack-tripleo-image-elements
sudo yum install -y openstack-tripleo-heat-templates

# TODO include tuskar-ui when available
sudo yum install -y openstack-tuskar
sudo yum install -y python-tuskarclient
# tuskar requires python-ipaddr, but it isn't a dep in the rpm
sudo yum install -y python-ipaddr
# Install patch so that we can patch merge.py for tuskar
sudo yum install -y patch

# TODO: move as a req in the rpm spec?
sudo yum -y install redhat-lsb-core

source ~/instack.answers

export LOCAL_IP
export DNSMASQ_START
export DNSMASQ_END
export LOCAL_INTERFACE
export MASQUERADE_NETWORK
export POWER_DRIVER
export VIRTUAL_POWER_USER
export VIRTUAL_POWER_HOST
export DHCP_START
export DHCP_END
export NETWORK_CIDR
export NETWORK_GATEWAY

sudo -E instack \
  -p /usr/share/diskimage-builder/elements/ \
     /usr/share/tripleo-image-elements/ \
     instack-undercloud/elements \
  -j instack-undercloud/json-files/fedora-20-undercloud-packages.json

sudo os-refresh-config

echo "install-undercloud Complete!"
