#!/bin/bash

set -eux

if [ -d /etc/tripleo ]; then
    TRIPLEO_ROOT=/etc/tripleo
else
    TRIPLEO_ROOT=/opt/stack/tripleo-incubator
fi

source /etc/sysconfig/stackrc

source tripleo-overcloud-passwords

export OVERCLOUD_IP=$(nova list | grep notCompute0.*ctlplane | sed  -e "s/.*=\\([0-9.]*\\).*/\1/")

source $TRIPLEO_ROOT/overcloudrc

export no_proxy=${no_proxy:-""}
export no_proxy=$no_proxy,$OVERCLOUD_IP

os-adduser -p $OVERCLOUD_DEMO_PASSWORD demo demo@example.com

nova flavor-delete m1.tiny
nova flavor-create m1.tiny 1 512 2 1

if [ ! -f cirros-0.3.0-x86_64-disk.img ]; then
    curl -L -O https://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-disk.img
fi

glance image-create --name user --public --disk-format qcow2 \
    --container-format bare --file cirros-0.3.0-x86_64-disk.img

wait_for 30 10 nova service-list --binary nova-compute 2\>/dev/null \| grep 'enabled.*\ up\ '

wait_for 30 10 neutron agent-list -f csv -c alive -c agent_type -c host \| grep "\":-).*Open vSwitch agent.*overcloud-novacompute\""

source $TRIPLEO_ROOT/overcloudrc-user

user-config

nova boot --key-name default --flavor m1.tiny --image user demo

wait_for 10 5 neutron port-list -f csv -c id --quote none \| grep id
PORT=$(neutron port-list -f csv -c id --quote none | tail -n1)
FLOATINGIP=$(neutron floatingip-create ext-net --port-id "${PORT//[[:space:]]/}" | awk '$2=="floating_ip_address" {print $4}')

neutron security-group-rule-create default --protocol icmp \
    --direction ingress --port-range-min 8 --port-range-max 8
neutron security-group-rule-create default --protocol tcp \
    --direction ingress --port-range-min 22 --port-range-max 22

wait_for 30 10 ping -c 1 $FLOATINGIP
