#!/usr/bin/python

import os
import subprocess
import sys

command = sys.argv[1:]
instack_root = os.environ.get("INSTACK_ROOT", os.getcwd())
command[0] = "%s/tripleo-incubator/scripts/%s" % (instack_root, command[0])

os.environ["PATH"] = "%s/tripleo-incubator/scripts:%s" % \
                        (instack_root, os.environ["PATH"])

sys.exit(subprocess.call(command))
