#!/bin/bash

set -eux
set -o pipefail

export RHOS_RELEASE=${RHOS_RELEASE:-"6"}
export RHOS_PUDDLE=${RHOS_PUDDLE:-""}

if ! rpm -q rhos-release; then
    rpm -Uvh http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm
fi

if [ -z "$RHOS_PUDDLE" ]; then
    rhos-release -d $RHOS_RELEASE
else
    rhos-release -d -p $RHOS_PUDDLE $RHOS_RELEASE
fi

yum-config-manager --enable rhelosp-rhel-7-server-opt
