#!/bin/bash
# just starts the discovery dnsmasq process
set -eux

install-packages dnsmasq dnsmasq-utils

# make sure tftpboot is labelled correctly
mkdir -p /tftpboot
restorecon -R /tftpboot

cat > /lib/systemd/system/openstack-ironic-discoverd-dnsmasq.service << eof
[Unit]
Description=PXE boot dnsmasq service for ironic-discoverd
After=openvswitch.service

[Service]
Type=forking
ExecStart=/sbin/dnsmasq --conf-file=/etc/ironic-discoverd/dnsmasq.conf

[Install]
WantedBy=multi-user.target
Alias=openstack-ironic-discoverd-dnsmasq.service
eof

# Enable the service
os-svc-enable -n openstack-ironic-discoverd-dnsmasq
