#!/bin/bash

set -eux

# TODO(dtantsur): replace with package
pip install ironic-discoverd
os-svc-daemon -n ironic-discoverd -i /usr -u root -c ironic-discoverd /etc/ironic-discoverd/discoverd.conf
install -d -m 0750 -o root -g root /etc/ironic-discoverd
