#!/bin/bash

set -eux

pip install ironic-discoverd
os-svc-daemon -n openstack-ironic-discoverd -i /usr -u root -c ironic-discoverd /etc/ironic-discoverd/discoverd.conf
install -d -m 0750 -o root -g root /etc/ironic-discoverd
install -d -m 0755 -o ironic -g ironic /tftpboot/pxelinux.cfg

# Enable the service
os-svc-enable -n openstack-ironic-discoverd
