#!/bin/bash

set -eux

# Clean up from any previous runs...
# TODO: figure out if we want upstream patches for this along the lines of a
# "cleanup" element that cleans up the environment at the very beginning of a
# run.
sudo rm -rf \
  /var/lib/use-ephemeral \
  /etc/neutron/plugin.ini \
  /opt/stack \
  /mnt/state \
  /var/lib/heat-cfntools \
  /etc/dib* \
  /usr/local/bin/* \
  /var/lib/rabbitmq \
  /var/log/rabbitmq

# Uninstall rabbitmq-server so that it gets reinstalled and recreates the
# needed dirs under /var
sudo yum -y erase rabbitmq-server
