#!/bin/bash

set -eux

OK_FILE=/opt/stack/.tuskar-setup

if [ -f $OK_FILE ]; then
    exit
fi

source /root/stackrc

export TUSKAR_URL=http://localhost:8585/

echo >> /etc/openstack-dashboard/local_settings
echo 'TUSKAR_ENDPOINT_URL = "http://127.0.0.1:8585"' >> /etc/openstack-dashboard/local_settings

pushd /usr/share/openstack-dashboard
python manage.py compress --force
popd

service httpd restart

os-svc-enable -n httpd
os-svc-enable -n openstack-tuskar-api

tuskar-dbsync --config-file /etc/tuskar/tuskar.conf
service openstack-tuskar-api restart
sleep 5

tuskar overcloud-role-create controller \
    --description 'Controller Node' \
    --image-name 'overcloud-control'

tuskar overcloud-role-create compute \
    --description 'Compute Nodes' \
    --image-name 'overcloud-compute'
    
tuskar overcloud-role-create blockstorage \
    --description 'Block Storage Nodes' \
    --image-name 'overcloud-cinder-volume'

tuskar overcloud-role-create swiftstorage \
    --description 'Swift Storage Nodes' \
    --image-name 'overcloud-swift-storage'

touch $OK_FILE
