#!/bin/bash

set -eux
set -o pipefail

if rpm -q fedora-release; then
    sudo curl -o /etc/yum.repos.d/slagle-openstack-m.repo https://copr.fedoraproject.org/coprs/slagle/openstack-m/repo/fedora-20/slagle-openstack-m-fedora-20.repo
elif rpm -q redhat-release; then
    sudo curl -o /etc/yum.repos.d/slagle-openstack-m.repo
https://copr.fedoraproject.org/coprs/slagle/openstack-m/repo/epel-7/slagle-openstack-m-epel-7.repo
fi
