#!/bin/bash

set -eux

# Workaround for:
# https://bugzilla.redhat.com/show_bug.cgi?id=1061045
# Go ahead and install mariadb-server, and remove the logfile with wrong
# permissions.
install-packages mariadb-galera-server
rm -f /var/log/mariadb/mariadb.log
