#!/bin/bash

set -eux

# Muse remove rdo-release-icehouse so that when it's installed via
# install-packages from the tie element, that doesn't fail since yum install is
# used vs yum update.
yum -y erase rdo-release-icehouse || true
