#!/bin/bash

set -eux
set -o pipefail

# This should run before configure.d/90-tuskar-db-sync

UNDERCLOUD_TUSKAR_PASSWORD=$(os-apply-config --key tuskar.service-password)

os-db-create tuskar tuskar $UNDERCLOUD_TUSKAR_PASSWORD
