#!/bin/bash
set -eu
set -o pipefail

if [ -n "${HORIZON_VENV_DIR:-}" ]; then
    set +u
    source $HORIZON_VENV_DIR/bin/activate
    set -u
    LOCAL_SETTINGS_FILE=$HORIZON_VENV_DIR/lib/python2.7/site-packages/openstack_dashboard/local/local_settings.py
    DJANGO_ADMIN=django-admin.py
else
    export PYTHONPATH=/usr/share/openstack-dashboard
    LOCAL_SETTINGS_FILE=/usr/share/openstack-dashboard/openstack_dashboard/local/local_settings.py
    DJANGO_ADMIN=django-admin
fi

source /root/stackrc

DJANGO_SETTINGS_MODULE=openstack_dashboard.settings $DJANGO_ADMIN collectstatic --noinput
DJANGO_SETTINGS_MODULE=openstack_dashboard.settings $DJANGO_ADMIN compress --force

if [ -n "${HORIZON_VENV_DIR:-}" ]; then
    set +u
    deactivate
    set -u
fi

os-svc-enable -n apache2
os-svc-restart -n apache2
